version: '3.8'

services:
  backend:
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    volumes:
      - stellarator-data:/data

  supervisor:
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
    volumes:
      - stellarator-data:/data

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
      target: builder
    command: npm run build && npm start
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
